<a href="https://colab.research.google.com/github/KayvanJ/FTI_project_example/blob/main/all_datasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
url_sp500 = 'https://raw.githubusercontent.com/KayvanJ/FTI_project_example/refs/heads/main/sp500.csv'
url_earthquake = 'https://raw.githubusercontent.com/KayvanJ/FTI_project_example/refs/heads/main/earthquakes.csv'
url_water = 'https://raw.githubusercontent.com/KayvanJ/FTI_project_example/refs/heads/main/zip_water_quality%20(1).csv'
url_ai = 'https://raw.githubusercontent.com/frontiertechinstitute/datasets/refs/heads/main/AI%20and%20Digital%20Media/Global_AI_Content_Impact_Dataset.csv'
url_disease = 'https://raw.githubusercontent.com/KayvanJ/FTI_project_example/refs/heads/main/chronic_disease_data.csv'

df_ai = pd.read_csv(url_ai)
df_earth = pd.read_csv(url_earthquake)
df_water = pd.read_csv(url_water)
df_sp500 = pd.read_csv(url_sp500)
df_disease = pd.read_csv(url_disease)

In [10]:
df_sp500.describe()

,SP500,Dividend,Earnings,Consumer Price Index,Long Interest Rate,Real Price,Real Dividend,Real Earnings,PE10
count,1865.000000,1865.000000,1865.000000,1865.000000,1865.000000,1865.000000,1865.000000,1865.000000,1865.000000
mean,471.260650,7.341378,17.253457,64.207480,4.410391,731.026804,19.865668,40.400402,15.983534
std,1078.137653,13.555434,34.337819,79.898101,2.351200,912.750421,13.665336,37.714948,8.378767
min,2.730000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,8.040000,0.400000,0.523300,10.100000,3.120000,207.500000,10.320000,15.290000,11.030000
50%,19.830000,0.856667,1.426000,19.900000,3.770000,315.610000,16.070000,26.010000,15.760000
75%,263.700000,7.356670,14.820000,105.300000,5.050000,802.570000,25.280000,49.350000,20.550000
max,7412.550000,68.710000,197.910000,306.130000,15.320000,5140.590000,71.220000,217.260000,44.200000

In [18]:
df_sp500.rename(columns = {'Consumer Price Index': "Consumer_Price_Index"})

,Date,SP500,Dividend,Earnings,Consumer_Price_Index,Long Interest Rate,Real Price,Real Dividend,Real Earnings,PE10
0,1871-01-01,4.44,0.26,0.4,12.46,5.32,109.05,6.39,9.82,0.0
1,1871-02-01,4.50,0.26,0.4,12.84,5.32,107.25,6.20,9.53,0.0
2,1871-03-01,4.61,0.26,0.4,13.03,5.33,108.27,6.11,9.39,0.0
3,1871-04-01,4.74,0.26,0.4,12.56,5.33,115.54,6.34,9.75,0.0
4,1871-05-01,4.86,0.26,0.4,12.27,5.33,121.22,6.48,9.98,0.0
...,...,...,...,...,...,...,...,...,...,...
1860,2026-01-01,6929.12,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0
1861,2026-02-01,6893.81,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0
1862,2026-03-01,6654.42,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0
1863,2026-04-01,6957.01,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0
1864,2026-05-01,7412.55,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0

In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import *

def do_LinReg(X_cols, y_col):
  X_train, X_test, y_train, y_test = train_test_split(X_cols, y_col, test_size=0.2, random_state=42)

  model = LinearRegression()
  model.fit(X_train, y_train)
  y_pred = model.predict(X_test)
  print(f"MSE: {mean_squared_error(y_test, y_pred)}")
  print("R^2: ",r2_score(y_test, y_pred))

  coefficients = pd.DataFrame(model.coef_, X_cols.columns, columns=['Coefficient'])
  return coefficients

do_LinReg(df_sp500[['SP500']],df_sp500['PE10'])

MSE: 66.32656984200989
R^2:  0.1247925343480194

       Coefficient
SP500     0.002128