<a href="https://colab.research.google.com/github/KayvanJ/FTI_project_example/blob/main/test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [4]:
url = 'https://raw.githubusercontent.com/KayvanJ/FTI_project_example/refs/heads/main/load_frcstd_7_day%20(17).csv'

df = pd.read_csv(url)

df.head()

,evaluated_at_datetime_utc,evaluated_at_datetime_ept,forecast_datetime_beginning_utc,forecast_datetime_beginning_ept,forecast_datetime_ending_utc,forecast_datetime_ending_ept,forecast_area,forecast_load_mw
0,7/9/2026 12:47:14 PM,7/9/2026 8:47:14 AM,7/9/2026 4:00:00 AM,7/9/2026 12:00:00 AM,7/9/2026 5:00:00 AM,7/9/2026 1:00:00 AM,AE/MIDATL,1311
1,7/9/2026 12:47:14 PM,7/9/2026 8:47:14 AM,7/9/2026 5:00:00 AM,7/9/2026 1:00:00 AM,7/9/2026 6:00:00 AM,7/9/2026 2:00:00 AM,AE/MIDATL,1224
2,7/9/2026 12:47:14 PM,7/9/2026 8:47:14 AM,7/9/2026 6:00:00 AM,7/9/2026 2:00:00 AM,7/9/2026 7:00:00 AM,7/9/2026 3:00:00 AM,AE/MIDATL,1170
3,7/9/2026 12:47:14 PM,7/9/2026 8:47:14 AM,7/9/2026 7:00:00 AM,7/9/2026 3:00:00 AM,7/9/2026 8:00:00 AM,7/9/2026 4:00:00 AM,AE/MIDATL,1137
4,7/9/2026 12:47:14 PM,7/9/2026 8:47:14 AM,7/9/2026 8:00:00 AM,7/9/2026 4:00:00 AM,7/9/2026 9:00:00 AM,7/9/2026 5:00:00 AM,AE/MIDATL,1134

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4200 entries, 0 to 4199
Data columns (total 8 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   evaluated_at_datetime_utc        4200 non-null   object
 1   evaluated_at_datetime_ept        4200 non-null   object
 2   forecast_datetime_beginning_utc  4200 non-null   object
 3   forecast_datetime_beginning_ept  4200 non-null   object
 4   forecast_datetime_ending_utc     4200 non-null   object
 5   forecast_datetime_ending_ept     4200 non-null   object
 6   forecast_area                    4200 non-null   object
 7   forecast_load_mw                 4200 non-null   int64
dtypes: int64(1), object(7)
memory usage: 262.6+ KB

In [6]:
df.columns

Index(['evaluated_at_datetime_utc', 'evaluated_at_datetime_ept',
       'forecast_datetime_beginning_utc', 'forecast_datetime_beginning_ept',
       'forecast_datetime_ending_utc', 'forecast_datetime_ending_ept',
       'forecast_area', 'forecast_load_mw'],
      dtype='object')

In [8]:
df.describe()

       forecast_load_mw
count       4200.000000
mean       13622.310476
std        24562.746703
min           86.000000
25%         2111.000000
50%         4368.000000
75%        14634.250000
max       156434.000000